name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions possible. Each node version will trigger the action
        node-version:
          - 18.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          repository: Informatievlaanderen/OSLOthema-template
          ref: config
          # The source folder contains the configuration files, as defined in the thema-template-repository
          path: source
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: standaardenregister
          # Target is the folder containing the content of thema-repository
          path: target
      # Extra step to debug the file structure
      - name: List file structure of source dir
        shell: bash
        run: |
          ls source
      - name: List file structure of target dir
        shell: bash
        run: |
          ls source/schemas
          ls target
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v2.4.0
        with:
          json_schema: source/schemas/configuration.json
          json_extension: json
          base_dir: target
          use_gitignore: false
