name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions. Each node version will trigger the action
        node-version:
          - 18.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: config # replace with your source branch name
          path: source

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: standaardenregister # replace with your target branch name
          path: target

      - name: Copy schema file into target branch
        run: |
          ls source/
          mkdir -p target/schemas
          cp -r source/schemas/* target/schemas/*
          ls target/schemas
      - name: List file structure of target dir
        run: |
          ls target/schemas
      - name: list folder structure
        run: |
          ls -a
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schemas/configuration.json
          INPUT_JSONS: "**.json"
