name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions. Each node version will trigger the action
        node-version:
          - 18.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: config # replace with your source branch name
          path: source

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: standaardenregister # replace with your target branch name
          path: target

      - name: Copy files
        run: |
          ls -la
  verify-json-validation:
    # Wait for previous job to make sure the schemas folder and configuration schema are created before running this job
    needs: copy-configuration-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # needed to fetch changes from other jobs, otherwise working on initial repo state
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: https://raw.githubusercontent.com/Informatievlaanderen/OSLOthema-template/config/schemas/configuration.json
          INPUT_JSONS: https://raw.githubusercontent.com/Informatievlaanderen/OSLOthema-airAndWater/master/config/OSLO-AirAndWater-Water-AP.json
