name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions. Each node version will trigger the action
        node-version:
          - 18.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: config
          path: source
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: standaardenregister
          path: target

      - name: List file structure of source dir
        shell: bash
        run: |
          ls source
      - name: List file structure of target dir
        shell: bash
        run: |
          ls source/schemas
          ls target
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          schema: source/schemas/configuration.json
          # files: target/ap-or-voc-config.json
          strict: false
