name: Validate JSONs

on: [push]

jobs:
  copy-configuration-files:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions. Each node version will trigger the action
        node-version:
          - 18.x
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: config
          path: source

      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: standaardenregister
          path: target

      - name: List file structure of target dir
        shell: bash
        run: |
          ls source
      - name: List file structure of target dir
        shell: bash
        run: |
          ls target
      - name: Copy schema files from source to target
        shell: bash
        run: |
          mkdir -p target/schemas && cp -r source/schemas/* target/schemas/*
      - name: list folder structure
        shell: bash
        run: |
          ls target
      # - name: Validate JSON
      #   uses: docker://orrosenblatt/validate-json-action:latest
      #   env:
      #     INPUT_SCHEMA: schemas/configuration.json
      #     INPUT_JSONS: "**.json"
