name: Convert the EAP file to JSON-ld

on:
  workflow_dispatch:
    inputs:
      #   uml-file:
      #     description: "Link to the (raw) UML file"
      #     required: true
      #   diagram-name:
      #     description: "Name of the diagram"
      #     required: true
      #     default: "OSLO-Persoon-Basis"
      # specification-type:
      #   description: "Type of the specification: Vocabulary | ApplicationProfile"
      #   default: "ApplicationProfile"
      #   required: true
      config-file:
        description: "Name of the config file. Example: mijn-applicatieprofiel-ap.json"
        default: "mijn-applicatieprofiel-ap.json"
        required: true
      # version-id:
      #   description: "Version of the specification"
      #   required: true
      #   default: "test/1"
    #   publication-environment:
    #     description: "Publication environment"
    #     required: true
    #     default: "https://data.vlaanderen.be"

jobs:
  convert-eap:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Different Node versions. Each node version will trigger the action
        node-version:
          - 20.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq

      - name: Install ea-converter
        run: npm install @oslo-flanders/ea-converter

      - name: Read key from configuration file
        id: read-config
        run: |
          diagram=$(jq -r '.[0].diagram' config/${{ github.event.inputs.config-file }})

          uml=$(jq -r '.[0].eap' config/${{ github.event.inputs.config-file }})

          type=$(jq -r '.[0].type' config/${{ github.event.inputs.config-file }})
          if [ "$type" = "ap" ]; then
          type="ApplicationProfile"
          elif [ "$type" = "voc" ]; then
          type="Vocabulary"
          fi

          echo "diagramName=$diagram" >> "$GITHUB_OUTPUT"
          echo "umlFile=$uml" >> "$GITHUB_OUTPUT"
          echo "specificationType=$type" >> "$GITHUB_OUTPUT"

      - name: Run oslo-converter-ea
        run: npx oslo-converter-ea --umlFile ${{ steps.read-config.outputs.umlFile }} --diagramName ${{ steps.read-config.outputs.diagramName }} --specificationType ${{ steps.read-config.outputs.specificationType }} --versionId test/1 --publicationEnvironment https://data.vlaanderen.be
